"""Nightly H/H round-robin rerun service.

Replaces the old static Dragapult vs TR-Mewtwo scheduled benchmark.

Instead of running a fixed matchup, the nightly job (and the Admin page manual
trigger) selects from *completed manual single-round H/H simulations* in
round-robin order, then creates a new queued simulation with fixed multi-round
coaching parameters.  The normal simulation queue/worker processes the generated
simulation — this service never runs matches directly.

Round-robin algorithm
---------------------
1. Build the sorted eligible source list (created_at ASC, id ASC).
2. Look up the current cycle number from nightly_hh_rerun_history.
3. Find source IDs already successfully rerun in the current cycle.
4. Select the first eligible source not yet rerun.
5. If all sources have been rerun, increment the cycle and start over.

Eligible source definition
--------------------------
- status = 'complete'
- game_mode = 'hh'
- num_rounds = 1
- user_deck_id is not NULL
- deck_mode = 'full'  (excludes old static scheduled runs which used 'none')
- At least one SimulationOpponent row exists
- Not a simulation generated by this rerun system
"""

from __future__ import annotations

import logging
import uuid
from typing import Any

from sqlalchemy import func, select, text
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.models import (
    Deck, NightlyHHRerunHistory, Simulation, SimulationOpponent,
)
from app.db.session import AsyncSessionLocal

logger = logging.getLogger(__name__)

# ── Fixed generated-simulation parameters ──────────────────────────────────────

# Stable advisory lock key for pg_try_advisory_xact_lock.
# Held for the duration of the create_rerun transaction so two concurrent
# callers (nightly cron + manual admin trigger) cannot both pass the
# queue-busy / source-selection critical section simultaneously.
_RERUN_ADVISORY_LOCK_KEY = 987_654_321

RERUN_GAME_MODE               = "hh"
RERUN_DECK_MODE               = "full"
RERUN_DECK_LOCKED             = False
RERUN_MATCHES_PER_OPPONENT    = 25
RERUN_NUM_ROUNDS              = 3
RERUN_TARGET_WIN_RATE         = 60   # % — matches Simulation model default
RERUN_TARGET_CONSECUTIVE_ROUNDS = 3
RERUN_TARGET_MODE             = "per_opponent"


# ── Eligibility query ──────────────────────────────────────────────────────────

async def get_eligible_sources(db: AsyncSession) -> list[Simulation]:
    """Return completed manual single-round H/H simulations eligible for rerun.

    Sorted deterministically by created_at ASC, id ASC for round-robin stability.
    """
    generated_result = await db.execute(
        select(NightlyHHRerunHistory.generated_simulation_id).where(
            NightlyHHRerunHistory.generated_simulation_id.is_not(None)
        )
    )
    generated_ids: set[uuid.UUID] = {row[0] for row in generated_result.all()}

    stmt = (
        select(Simulation)
        .join(SimulationOpponent,
              SimulationOpponent.simulation_id == Simulation.id)
        .where(
            Simulation.status == "complete",
            Simulation.game_mode == "hh",
            Simulation.num_rounds == 1,
            Simulation.user_deck_id.is_not(None),
            Simulation.deck_mode == "full",
        )
        .distinct()
        .order_by(Simulation.created_at.asc(), Simulation.id.asc())
    )
    all_sims = (await db.execute(stmt)).scalars().all()
    return [s for s in all_sims if s.id not in generated_ids]


# ── Cycle / round-robin helpers ────────────────────────────────────────────────

async def _get_cycle_info(
    eligible_ids: list[uuid.UUID],
    db: AsyncSession,
) -> tuple[int, set[uuid.UUID]]:
    """Return (current_cycle_number, source_ids_already_done_this_cycle)."""
    max_result = await db.execute(
        select(func.max(NightlyHHRerunHistory.cycle_number))
    )
    current_cycle: int = max_result.scalar() or 1

    done_result = await db.execute(
        select(NightlyHHRerunHistory.source_simulation_id).where(
            NightlyHHRerunHistory.cycle_number == current_cycle,
            NightlyHHRerunHistory.status == "created",
        )
    )
    done_ids: set[uuid.UUID] = {row[0] for row in done_result.all()}

    eligible_set = set(eligible_ids)
    remaining = eligible_set - done_ids
    if eligible_set and not remaining:
        # All eligible sources done — advance cycle
        current_cycle += 1
        done_ids = set()

    return current_cycle, done_ids


def _select_next_source(
    eligible: list[Simulation],
    done_ids: set[uuid.UUID],
) -> Simulation | None:
    """Return the first eligible source not already rerun in this cycle."""
    for sim in eligible:
        if sim.id not in done_ids:
            return sim
    return None


# ── Core service ───────────────────────────────────────────────────────────────

async def create_rerun(triggered_by: str, db: AsyncSession) -> dict:
    """Create one queued rerun simulation and record history.

    Returns a dict with 'status': 'created' | 'skipped' | 'failed'.
    The caller is responsible for dispatching the Celery task when status='created'.
    """
    # 0. Advisory lock — prevents concurrent duplicate reruns
    lock_result = await db.execute(
        text("SELECT pg_try_advisory_xact_lock(:key)"),
        {"key": _RERUN_ADVISORY_LOCK_KEY},
    )
    if not lock_result.scalar():
        return {"status": "skipped", "reason": "nightly H/H rerun already in progress"}

    # 1. Queue-busy guard
    active_count: int = (await db.execute(
        select(func.count(Simulation.id)).where(
            Simulation.status.in_(["queued", "pending", "running"])
        )
    )).scalar() or 0
    if active_count > 0:
        return {"status": "skipped", "reason": "simulation queue busy"}

    # 2. Eligible sources
    eligible = await get_eligible_sources(db)
    if not eligible:
        return {"status": "skipped", "reason": "no eligible source simulations"}

    eligible_ids = [s.id for s in eligible]

    # 3. Round-robin selection
    cycle_number, done_ids = await _get_cycle_info(eligible_ids, db)
    source_sim = _select_next_source(eligible, done_ids)
    if source_sim is None:
        return {"status": "skipped", "reason": "no eligible source simulations"}

    # 4. Fetch opponents
    opponents = (await db.execute(
        select(SimulationOpponent).where(
            SimulationOpponent.simulation_id == source_sim.id
        )
    )).scalars().all()

    # 5. Create generated simulation and history row
    try:
        gen_sim = Simulation(
            status="pending",
            game_mode=RERUN_GAME_MODE,
            deck_mode=RERUN_DECK_MODE,
            deck_locked=RERUN_DECK_LOCKED,
            user_deck_id=source_sim.user_deck_id,
            user_deck_name=source_sim.user_deck_name,
            matches_per_opponent=RERUN_MATCHES_PER_OPPONENT,
            num_rounds=RERUN_NUM_ROUNDS,
            target_win_rate=RERUN_TARGET_WIN_RATE,
            target_consecutive_rounds=RERUN_TARGET_CONSECUTIVE_ROUNDS,
            target_mode=RERUN_TARGET_MODE,
        )
        db.add(gen_sim)
        await db.flush()

        for opp in opponents:
            db.add(SimulationOpponent(
                simulation_id=gen_sim.id,
                deck_id=opp.deck_id,
                deck_name=opp.deck_name,
            ))

        history_row = NightlyHHRerunHistory(
            source_simulation_id=source_sim.id,
            generated_simulation_id=gen_sim.id,
            cycle_number=cycle_number,
            source_user_deck_id=source_sim.user_deck_id,
            source_user_deck_name=source_sim.user_deck_name,
            source_opponent_deck_ids=[str(opp.deck_id) for opp in opponents],
            source_opponent_deck_names=[opp.deck_name for opp in opponents],
            status="created",
            triggered_by=triggered_by,
        )
        db.add(history_row)
        await db.commit()

    except Exception as exc:
        logger.exception("Failed to create nightly H/H rerun from source %s", source_sim.id)
        try:
            await db.rollback()
            async with AsyncSessionLocal() as err_db:
                err_db.add(NightlyHHRerunHistory(
                    source_simulation_id=source_sim.id,
                    generated_simulation_id=None,
                    cycle_number=cycle_number,
                    source_user_deck_id=source_sim.user_deck_id,
                    source_user_deck_name=source_sim.user_deck_name,
                    source_opponent_deck_ids=[str(o.deck_id) for o in opponents],
                    source_opponent_deck_names=[o.deck_name for o in opponents],
                    status="failed",
                    triggered_by=triggered_by,
                    error_message=str(exc)[:1000],
                ))
                await err_db.commit()
        except Exception:
            logger.exception("Could not record failed rerun history for source %s", source_sim.id)
        return {"status": "failed", "reason": str(exc)[:500]}

    return {
        "status": "created",
        "source_simulation_id": str(source_sim.id),
        "generated_simulation_id": str(gen_sim.id),
        "cycle_number": cycle_number,
    }


# ── Status / preview helpers for Admin API ─────────────────────────────────────

async def get_rerun_status(db: AsyncSession) -> dict:
    """Return status payload for GET /api/admin/nightly-hh-rerun/status."""
    eligible = await get_eligible_sources(db)
    eligible_ids = [s.id for s in eligible]

    if eligible_ids:
        cycle_number, done_ids = await _get_cycle_info(eligible_ids, db)
        completed_count = len(done_ids & set(eligible_ids))
    else:
        cycle_number = 1
        completed_count = 0

    last_result = await db.execute(
        select(NightlyHHRerunHistory)
        .order_by(NightlyHHRerunHistory.created_at.desc())
        .limit(1)
    )
    last_row: NightlyHHRerunHistory | None = last_result.scalar_one_or_none()

    return {
        "enabled": True,
        "schedule": "02:00 UTC nightly",
        "eligible_source_count": len(eligible),
        "current_cycle": cycle_number,
        "current_cycle_completed_count": completed_count,
        "current_cycle_total_count": len(eligible),
        "last_rerun": _history_row_to_dict(last_row) if last_row else None,
        "fixed_parameters": {
            "deck_locked": RERUN_DECK_LOCKED,
            "game_mode": RERUN_GAME_MODE,
            "matches_per_opponent": RERUN_MATCHES_PER_OPPONENT,
            "num_rounds": RERUN_NUM_ROUNDS,
            "target_win_rate": RERUN_TARGET_WIN_RATE,
            "target_consecutive_rounds": RERUN_TARGET_CONSECUTIVE_ROUNDS,
            "target_mode": RERUN_TARGET_MODE,
        },
    }


async def preview_rerun(db: AsyncSession) -> dict:
    """Return preview payload for GET /api/admin/nightly-hh-rerun/preview.

    Does NOT create any simulation or history row.
    """
    active_count: int = (await db.execute(
        select(func.count(Simulation.id)).where(
            Simulation.status.in_(["queued", "pending", "running"])
        )
    )).scalar() or 0
    if active_count > 0:
        return {"status": "skipped", "reason": "simulation queue busy"}

    eligible = await get_eligible_sources(db)
    if not eligible:
        return {"status": "skipped", "reason": "no eligible source simulations"}

    eligible_ids = [s.id for s in eligible]
    cycle_number, done_ids = await _get_cycle_info(eligible_ids, db)
    source_sim = _select_next_source(eligible, done_ids)
    if source_sim is None:
        return {"status": "skipped", "reason": "no eligible source simulations"}

    opponents = (await db.execute(
        select(SimulationOpponent).where(
            SimulationOpponent.simulation_id == source_sim.id
        )
    )).scalars().all()

    # Look up user deck name if missing on the simulation row
    user_deck_name = source_sim.user_deck_name
    if not user_deck_name and source_sim.user_deck_id:
        deck_row = (await db.execute(
            select(Deck).where(Deck.id == source_sim.user_deck_id)
        )).scalar_one_or_none()
        if deck_row:
            user_deck_name = deck_row.name

    return {
        "status": "ok",
        "cycle_number": cycle_number,
        "next_source": {
            "simulation_id": str(source_sim.id),
            "created_at": source_sim.created_at.isoformat() if source_sim.created_at else None,
            "user_deck_id": str(source_sim.user_deck_id) if source_sim.user_deck_id else None,
            "user_deck_name": user_deck_name,
            "opponents": [
                {"deck_id": str(opp.deck_id), "deck_name": opp.deck_name}
                for opp in opponents
            ],
        },
        "generated_parameters": {
            "deck_locked": RERUN_DECK_LOCKED,
            "game_mode": RERUN_GAME_MODE,
            "deck_mode": RERUN_DECK_MODE,
            "matches_per_opponent": RERUN_MATCHES_PER_OPPONENT,
            "num_rounds": RERUN_NUM_ROUNDS,
            "target_win_rate": RERUN_TARGET_WIN_RATE,
            "target_consecutive_rounds": RERUN_TARGET_CONSECUTIVE_ROUNDS,
            "target_mode": RERUN_TARGET_MODE,
        },
    }


def _history_row_to_dict(row: NightlyHHRerunHistory) -> dict[str, Any]:
    return {
        "id": str(row.id),
        "source_simulation_id": str(row.source_simulation_id),
        "generated_simulation_id": (
            str(row.generated_simulation_id) if row.generated_simulation_id else None
        ),
        "cycle_number": row.cycle_number,
        "source_user_deck_name": row.source_user_deck_name,
        "source_opponent_deck_names": row.source_opponent_deck_names,
        "status": row.status,
        "triggered_by": row.triggered_by,
        "error_message": row.error_message,
        "created_at": row.created_at.isoformat() if row.created_at else None,
    }
