"""initial_schema

Revision ID: 4afceada2d2a
Revises: 
Create Date: 2026-04-26 19:50:09.858958

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision: str = '4afceada2d2a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('tcgdex_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('set_abbrev', sa.Text(), nullable=False),
    sa.Column('set_number', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('subcategory', sa.Text(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evolve_from', sa.Text(), nullable=True),
    sa.Column('stage', sa.Text(), nullable=True),
    sa.Column('attacks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('abilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resistances', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retreat_cost', sa.Integer(), nullable=True),
    sa.Column('regulation_mark', sa.Text(), nullable=True),
    sa.Column('rarity', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('raw_tcgdex', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('tcgdex_id')
    )
    op.create_table('decks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('archetype', sa.Text(), nullable=True),
    sa.Column('deck_text', sa.Text(), nullable=False),
    sa.Column('card_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_performance',
    sa.Column('card_tcgdex_id', sa.Text(), nullable=False),
    sa.Column('games_included', sa.Integer(), nullable=True),
    sa.Column('games_won', sa.Integer(), nullable=True),
    sa.Column('total_kos', sa.Integer(), nullable=True),
    sa.Column('total_damage', sa.BigInteger(), nullable=True),
    sa.Column('total_prizes', sa.Integer(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['card_tcgdex_id'], ['cards.tcgdex_id'], ),
    sa.PrimaryKeyConstraint('card_tcgdex_id')
    )
    op.create_table('deck_cards',
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('card_tcgdex_id', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_tcgdex_id'], ['cards.tcgdex_id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deck_id', 'card_tcgdex_id')
    )
    op.create_table('simulations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('game_mode', sa.Text(), nullable=False),
    sa.Column('deck_mode', sa.Text(), nullable=False),
    sa.Column('deck_locked', sa.Boolean(), nullable=True),
    sa.Column('user_deck_id', sa.UUID(), nullable=True),
    sa.Column('matches_per_opponent', sa.Integer(), nullable=False),
    sa.Column('num_rounds', sa.Integer(), nullable=False),
    sa.Column('target_win_rate', sa.Integer(), nullable=False),
    sa.Column('target_mode', sa.Text(), nullable=False),
    sa.Column('excluded_cards', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_win_rate', sa.Integer(), nullable=True),
    sa.Column('rounds_completed', sa.Integer(), nullable=True),
    sa.Column('total_matches', sa.Integer(), nullable=True),
    sa.Column('user_deck_name', sa.Text(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('starred', sa.Boolean(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_deck_id'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deck_mutations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('simulation_id', sa.UUID(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('card_removed', sa.Text(), nullable=False),
    sa.Column('card_added', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('simulation_id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('deck_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('win_rate', sa.Integer(), nullable=True),
    sa.Column('total_matches', sa.Integer(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_id', 'round_number')
    )
    op.create_table('simulation_opponents',
    sa.Column('simulation_id', sa.UUID(), nullable=False),
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('deck_name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('simulation_id', 'deck_id')
    )
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('simulation_id', sa.UUID(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('opponent_deck_id', sa.UUID(), nullable=True),
    sa.Column('winner', sa.Text(), nullable=False),
    sa.Column('win_condition', sa.Text(), nullable=False),
    sa.Column('total_turns', sa.Integer(), nullable=False),
    sa.Column('p1_prizes_taken', sa.Integer(), nullable=False),
    sa.Column('p2_prizes_taken', sa.Integer(), nullable=False),
    sa.Column('prize_progression', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('p1_deck_name', sa.Text(), nullable=True),
    sa.Column('p2_deck_name', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['opponent_deck_id'], ['decks.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=True),
    sa.Column('simulation_id', sa.UUID(), nullable=True),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Text(), nullable=False),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('card_played', sa.Text(), nullable=True),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('legal_action_count', sa.Integer(), nullable=True),
    sa.Column('game_state_summary', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('turn', sa.Integer(), nullable=True),
    sa.Column('player', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'sequence')
    )
    # Indexes from Appendix B
    op.create_index("idx_cards_name", "cards", ["name"],
                    postgresql_using="gin",
                    postgresql_ops={"name": "gin_trgm_ops"})
    op.create_index("idx_cards_category", "cards", ["category"])
    op.create_index("idx_cards_set", "cards", ["set_abbrev"])
    op.create_index("idx_simulations_status", "simulations", ["status"])
    op.create_index("idx_simulations_created", "simulations", ["created_at"])
    op.create_index("idx_matches_simulation", "matches", ["simulation_id"])
    op.create_index("idx_matches_round", "matches", ["round_id"])
    op.create_index("idx_match_events_match", "match_events", ["match_id"])
    op.create_index("idx_decisions_match", "decisions", ["match_id"])
    op.create_index("idx_decisions_card", "decisions", ["card_played"])
    op.create_index("idx_mutations_simulation", "deck_mutations", ["simulation_id"])
    op.create_index("idx_embeddings_source", "embeddings", ["source_type", "source_id"])
    op.execute(
        "CREATE INDEX idx_embeddings_vector ON embeddings "
        "USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_events')
    op.drop_table('decisions')
    op.drop_table('matches')
    op.drop_table('simulation_opponents')
    op.drop_table('rounds')
    op.drop_table('deck_mutations')
    op.drop_table('simulations')
    op.drop_table('deck_cards')
    op.drop_table('card_performance')
    op.drop_table('embeddings')
    op.drop_table('decks')
    op.drop_table('cards')
    # ### end Alembic commands ###
